name: teamSync Update Automatically

on:
  schedule:
    - cron: '00 00 * * 1' # UTC time at 00:00 on Monday

jobs:
  check-permissions:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
          fetch-depth: 0
      
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'adopt'
        
    - name: Build project
      run: mvn clean install

    - name: Update all yml files in permissions directory
      run: |
        echo "Updating all permissions files..."
        for file in permissions/*.yml; do  
          file="${file#permissions/}"
          echo "Updating the team in: $file"
          java -jar target/github_team_sync.jar "$file"
        done
        echo "All permissions files updated."
      env:
        GITHUB_OAUTH: ${{ secrets.HOSTING_PAT }}
